### ISSUE TITLE
setWeight() turns value in gram to kg

### ISSUE THREAD

**Issue by Roywcm** [myparcelnl/sdk#188] opened 2019-11-27 13:13 UTC
Hi,

When I try to add the weight to MyParcelCustomsItem, the weight on the generated COMMERCIAL INVOICE turns into kilograms. 

MyParcelCustomsItem()->setWeight(600) turns into 600kg on the commercial invoice. 
I tried to use 0.6, but this turns into 0kg. 

I think there is a bug here. 

I'm using version 3.1

**Comment by Roywcm** [comment] 2019-12-09 09:55
Any updates about this? I need this to activate international shipping. My client is waiting.

**Comment by RichardPerdaan** [comment] 2019-12-09 10:41
Hi @Roywcm,

Thank you for reporting this issue.
It seems that the problem is not in the SDK but in the MyParcel API. I have passed this to my colleague and hey will investigate further. I'll keep you informed.

**Comment by Roywcm** [comment] 2019-12-09 10:41
Ok, thanks

**Comment by RichardPerdaan** [comment] 2019-12-16 15:04
Hi @Roywcm 

It is going wrong on the PostNL side. We have therefore passed this to theme.

Because the cause has been found and we cannot do anything about this within MyParcel, I close the issue.

**Closed by RichardPerdaan** 2019-12-16 15:04 UTC
Labels: bug

**Comment by Roywcm** [comment] 2019-12-16 15:19
Ok, is there a way for me to follow the progress on this bug on PostNL's side?

**Comment by RichardPerdaan** [comment] 2019-12-17 08:47
Unfortunately it is not possible to follow the progress, it is unfortunately not possible for me either.

**Comment by Roywcm** [comment] 2019-12-18 10:14
Ok, is there a temporary solution we can use? Or can we use shipping labels with 600kilo on the forms?

**Comment by RichardPerdaan** [comment] 2019-12-18 15:41
Hi @Roywcm,
Unfortunately I don't know any temporary solution for now. 
It will not cause any problems if you can see 600 kilos on the forms

**Comment by Roywcm** [comment] 2019-12-18 15:46
Ah ok, thnx
